/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as QuizzesCreateRouteImport } from './routes/quizzes/create'
import { Route as QuizzesIdRouteImport } from './routes/quizzes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesCreateRoute = QuizzesCreateRouteImport.update({
  id: '/quizzes/create',
  path: '/quizzes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quizzes/$id' | '/quizzes/create' | '/quizzes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quizzes/$id' | '/quizzes/create' | '/quizzes'
  id: '__root__' | '/' | '/quizzes/$id' | '/quizzes/create' | '/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizzesIdRoute: typeof QuizzesIdRoute
  QuizzesCreateRoute: typeof QuizzesCreateRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/create': {
      id: '/quizzes/create'
      path: '/quizzes/create'
      fullPath: '/quizzes/create'
      preLoaderRoute: typeof QuizzesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizzesIdRoute: QuizzesIdRoute,
  QuizzesCreateRoute: QuizzesCreateRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
